### PR TITLE
migarate to AndroidX

### PR DESCRIPTION
**Pull request by asaarnak**

### CODE REVIEW

**Comment by tjarvstrand** [comment]
Hi @asaarnak, sorry for the late response. I thought I was watching this repo but apparently not.

Am I correct in assuming that this should only affect how tests are run?

**Comment by asaarnak** [comment]
I think so, haven't written android tests

**Comment by asaarnak** [comment]
@tjarvstrand 
https://developer.android.com/training/testing/instrumented-tests/androidx-test-libraries/runner

The [AndroidJUnitRunner](https://developer.android.com/reference/androidx/test/runner/AndroidJUnitRunner) class is a [JUnit](http://junit.org/junit4/) test runner that lets you run instrumented [JUnit 4](https://junit.org/junit4/) tests on Android devices, including those using the [Espresso](https://developer.android.com/training/testing/espresso), [UI Automator](https://developer.android.com/training/testing/ui-automator), and [Compose](https://developer.android.com/jetpack/compose/testing) testing frameworks.

**Comment by asaarnak** [comment]
@tjarvstrand We have been using this with fork now for some time with no issues.

**Comment by tjarvstrand** [comment]
Thanks! Sorry for the delay

**Pull request merged**
