### PR TITLE
feat: support wasm compilation

### LINKED ISSUE #29: Migrate to package:web for Wasm support
Flutter supports building Flutter for web using Wasm.
For this to work, [dart:js_interop](https://api.dart.dev/stable/dart-js_interop) has to be used instead of `dart:js_util` & `package:js/js.dart`. 

https://docs.flutter.dev/platform-integration/web/wasm

### PR DESCRIPTION
**Pull request by renancaraujo**
This fixes #29

### CODE REVIEW

**Comment by bwhiteFC** [comment]
@tjarvstrand can you please merge this. Thanks

**Comment by tjarvstrand** [comment]
Hey, sorry for the delay. I've been extremely busy of late. The good news is that July is set to be more quiet so I'll make sure to get to this then!

**Comment by renancaraujo** [comment]
@tjarvstrand thank you so much!

**Comment by tjarvstrand** [comment]
Change looks reasonable to me. Tried it out and it seems to work :)

**Comment by tjarvstrand** [comment]
Just published 2.0.0 with these changes

**Comment by kuhnroyal** [comment]
This PR introduced a 2 year old unused dependency with a GPL-3 license.
You don't need https://pub.dev/packages/js_interop to use `dat:js_interop` - please revert the dependency change and publish a fix :)

**Comment by tjarvstrand** [comment]
Oh, oops.

Just published 2.0.1 without unused dependencies.

**Pull request merged**
