### PR TITLE
feat: add Windows support

### LINKED ISSUE #22: Support for Windows
Hello, I was wondering if there would be support for Windows at some point? Is there any technical difficulties to get the IANA timezone on windows?

### PR DESCRIPTION
**Pull request by domyd**
Hi!

This adds support for the Windows platform, and fixes #22.

This is implemented using the [ICU library that ships with Windows](https://learn.microsoft.com/en-us/windows/win32/intl/international-components-for-unicode--icu-?redirectedfrom=MSDN). Since I'm only including `icu.h` and linking `icu.lib` here, Windows versions earlier than Windows 10 1903 aren't supported. If this is an issue, this could be extended back to 1703 with more Windows-version-specific `#include`s and linking (as described in the link above).

I've split this up into three commits for easier reviewing 🙂

### CODE REVIEW

**Comment by tjarvstrand** [comment]
This is great, thank you!

Unfortunately, given that I don't have any way to test this and I have zero experience working with windows, my best assessment is basically that I can't see anything in here that would be outright harmful :D I'm just going to have to take your word for it that this is working as intended.

Would you say that this is ready to be merged?

**Comment by tjarvstrand** [comment]
> As for testing: best way I can think of is doing it in CI by setting the runner's time zone and region to different values and checking that the plugin returns the correct IANA identifier. It doesn't look like it's too much effort, so if you want I can add that.

Thanks, that would be brilliant!

**Comment by domyd** [comment]
I added the tests 🙂

The `run_integration_test_windows.ps1` script has a set of test parameters and loops through them, setting the Windows system's time zone and region and then running the `local_timezone_test.dart` integration test and verifying that the output is as expected. I've tried to keep it fairly general so that extending these integration tests to run on other platforms in the future is as easy as possible.

To keep the integration test simple I split the timezone label into its own `Text` widget, and since I was already at it I touched up the UI just a little bit, and added a refresh button (which I found useful for development). Hope you don't mind!

**Comment by tjarvstrand** [comment]
Amazing, thanks!

**Comment by tjarvstrand** [comment]
Published as 2.1.0

**Comment by hiddify-com** [comment]
Thanks for your great contribution.
Will it raise an exception for windows earlier than 1706?

**Comment by domyd** [comment]
It will most likely not even build on Windows earlier than 1709. When built on a newer Windows machine and deployed to a <1709 one, you'll get an error message on startup about a missing DLL.

**Pull request merged**
